# -*- coding: utf-8 -*-
"""norn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8FP6NfXFBZO3DuG4GLbME5mdACkoD6p

# YANDEX
"""


!curl --request POST --data '{"yandexPassportOauthToken":AQVNxK05kh4VaOEU4Fi8J3NNTp6-HXf7zBqH3L_l}' https://iam.api.cloud.yandex.net/iam/v1/tokens

!pip install yandex-chain
from yandex_chain import YandexLLM, YandexGPTModel

LLM = YandexLLM(model=YandexGPTModel.Pro, folder_id='...', iam_token='...')
print(LLM._modelUri)
print(LLM("Бу! Испугался? Не бойся. Я друг, я тебя не обижу."))

"""# DP"""

!pip install -q deeppavlov
# !python -m deeppavlov install entity_extraction_en

en_example = ['''Market review
As global cobalt price went up in Jan. 2013, Chinese cobalt still showed a weak tendency, thus
the spread was narrowing. The average Chinese cobalt price was 209,000yuan/t in Jan.''']
ru_example = ['''Система VacuRoll состоит из верхнего и нижнего валка (ов). Вакуум подается вовнутрь
пустотелых валков с пористым покрытием. Избыточная жидкость втягивается в валок и
удаляется с полосы. Загрязнение вкатывается в покрытие валка в ходе циклов
вращательного сжатия/сброса давления. Уровень шума очень низкий – около 65 дБА и не
зависит от скорости движения полос.
Максимальная скорость движения полосы – до 1585 м/мин. Максимальная температура
поверхности не должна превышать 120 °C. Валки приводятся в движение трением и
вращаются с той же скоростью, что и полоса в конечной последовательности проходов.
Сила трения может адаптироваться к рабочим условиям и свойствам материала благодаря
регулировке пневматического нажимного цилиндра. Остаток жидкости и других веществ
на полосе будет также удален.''']

import warnings
warnings.filterwarnings('ignore')

from deeppavlov import build_model

ed_en = build_model('entity_detection_en', download=True, install=True)
ed_en(['Forrest Gump is a comedy-drama film directed by Robert Zemeckis and written by Eric Roth.'])

ed_ru = build_model('entity_detection_ru', download=True, install=True)
ed_ru(['Москва — столица России, центр Центрального федерального округа и центр Московской области.'])

el_en = build_model('entity_linking_en', download=True, install=True)
el_en([['forrest gump', 'robert zemeckis', 'eric roth']],
      [['WORK_OF_ART', 'PERSON', 'PERSON']],
      [[1.0, 1.0, 1.0]],
      [['Forrest Gump is a comedy-drama film directed by Robert Zemeckis and written by Eric Roth.']],
      [[(0, 12), (48, 63), (79, 88)]],
      [[(0, 89)]])

el_ru = build_model('entity_linking_ru', download=True, install=True)

el_ru([['москва', 'россии', 'центрального федерального округа', 'московской области']],
      [['CITY', 'COUNTRY', 'LOC', 'LOC']],
      [[1.0, 1.0, 1.0, 1.0]],
      [['Москва — столица России, центр Центрального федерального округа и центр Московской области.']],
      [[(0, 6), (17, 23), (31, 63), (72, 90)]],
      [[(0, 91)]])

ex_en = build_model('entity_extraction_en', download=True, install=True)
ex_en(['Forrest Gump is a comedy-drama film directed by Robert Zemeckis and written by Eric Roth.'])

ex_ru = build_model('entity_extraction_ru', download=True, install=True)

ex_ru(['Москва — столица России, центр Центрального федерального округа и центр Московской области.'])

"""# OWL

## старое
"""

import datetime
from owlready2 import *

# 1. Создаем новую пустую онтологию в локальном репозитории
onto = get_ontology("http://example.org")

with onto:
    # --- ВСПОМОГАТЕЛЬНЫЕ КЛАССЫ ---
    class Country(Thing):
        """Класс для представления стран."""
        pass

    # --- ОСНОВНЫЕ КЛАССЫ ОНТОЛОГИИ ---
    class Publication(Thing): pass
    class Expert(Thing): pass
    class Team(Thing): pass
    class Facility(Thing): pass
    class Experiment(Thing): pass
    class Material(Thing): pass
    class Equipment(Thing): pass
    class Process(Thing): pass
    class Property(Thing): pass

    # ==========================================
    # 1. СВОЙСТВА ДЛЯ КЛАССА PUBLICATION
    # ==========================================
    class pub_title(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_date(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [datetime.date]

    class pub_country(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_language(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_type(DataProperty, FunctionalProperty):
        domain = [Publication]
        # Фиксированный список значений через OneOf
        range = [OneOf(["статья", "обзор", "отчёт", "протокол", "патент", "справочник", "нормативный материал"])]

    class pub_access_type(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [OneOf(["открытый", "закрытый"])]

    class pub_reliability(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [OneOf(["высокая", "средняя", "низкая"])]

    class pub_conclusions(DataProperty):  # Множественное свойство (список str)
        domain = [Publication]
        range = [str]

    class pub_full_text(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_additional_materials(DataProperty):  # Список файлов (пути или имена в str)
        domain = [Publication]
        range = [str]

    # Свойства объектов для Publication
    class has_author(ObjectProperty):
        domain = [Publication]
        range = [Expert | Team]  # Автор может быть либо Экспертом, либо Командой

    class pub_facility(ObjectProperty, FunctionalProperty):
        domain = [Publication]
        range = [Facility]

    class pub_keywords(ObjectProperty):
        domain = [Publication]
        range = [Material | Equipment | Experiment | Process | Property | Facility]

    # ==========================================
    # 2. СВОЙСТВА ДЛЯ КЛАССА EXPERT
    # ==========================================
    class expert_name(DataProperty, FunctionalProperty):
        domain = [Expert]
        range = [str]

    class expert_qualification(DataProperty, FunctionalProperty):
        domain = [Expert]
        range = [str]

    class expert_country(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Country]

    class expert_facility(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Facility]

    class expert_team(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Team]

    class expert_publications(ObjectProperty):
        domain = [Expert]
        range = [Publication]

    # ==========================================
    # 3. СВОЙСТВА ДЛЯ КЛАССА TEAM
    # ==========================================
    class team_name(DataProperty, FunctionalProperty):
        domain = [Team]
        range = [str]

    class team_country(ObjectProperty, FunctionalProperty):
        domain = [Team]
        range = [Country]

    class team_facility(ObjectProperty, FunctionalProperty):
        domain = [Team]
        range = [Facility]

    class team_members(ObjectProperty):
        domain = [Team]
        range = [Expert]

    class team_publications(ObjectProperty):
        domain = [Team]
        range = [Publication]

    # ==========================================
    # 4. СВОЙСТВА ДЛЯ КЛАССА FACILITY
    # ==========================================
    class facility_name(DataProperty, FunctionalProperty):
        domain = [Facility]
        range = [str]

    class facility_country(ObjectProperty, FunctionalProperty):
        domain = [Facility]
        range = [Country]

    class facility_teams(ObjectProperty):
        domain = [Facility]
        range = [Team]

    class facility_employees(ObjectProperty):
        domain = [Facility]
        range = [Expert]

    class facility_publications(ObjectProperty):
        domain = [Facility]
        range = [Publication]

    # ==========================================
    # 5. СВОЙСТВА ДЛЯ КЛАССА EXPERIMENT
    # ==========================================
    class experiment_name(DataProperty, FunctionalProperty):
        domain = [Experiment]
        range = [str]

    class experiment_conditions(DataProperty):  # Список параметров в формате строк
        domain = [Experiment]
        range = [str]

    class experiment_data(DataProperty):  # Список файлов данных
        domain = [Experiment]
        range = [str]

    class experiment_conclusions(DataProperty):  # Список выводов
        domain = [Experiment]
        range = [str]

    class experiment_publications(ObjectProperty):
        domain = [Experiment]
        range = [Publication]

    class experiment_materials(ObjectProperty):
        domain = [Experiment]
        range = [Material]

    class experiment_processes(ObjectProperty):
        domain = [Experiment]
        range = [Process]

    class experiment_equipment(ObjectProperty):
        domain = [Experiment]
        range = [Equipment]

    # ==========================================
    # 6. СВОЙСТВА ДЛЯ КЛАССА MATERIAL
    # ==========================================
    class material_name(DataProperty, FunctionalProperty):
        domain = [Material]
        range = [str]

    class material_properties(ObjectProperty):
        domain = [Material]
        range = [Property]

    class material_related_works(ObjectProperty):
        domain = [Material]
        range = [Publication | Experiment]

    # ==========================================
    # 7. СВОЙСТВА ДЛЯ КЛАССА EQUIPMENT
    # ==========================================
    class equipment_name(DataProperty, FunctionalProperty):
        domain = [Equipment]
        range = [str]

    class equipment_properties(ObjectProperty):
        domain = [Equipment]
        range = [Property]

    class equipment_related_works(ObjectProperty):
        domain = [Equipment]
        range = [Publication | Experiment]

    # ==========================================
    # 8. СВОЙСТВА ДЛЯ КЛАССА PROCESS
    # ==========================================
    class process_name(DataProperty, FunctionalProperty):
        domain = [Process]
        range = [str]

    class process_description(DataProperty, FunctionalProperty):
        domain = [Process]
        range = [str]

    class process_result(DataProperty, FunctionalProperty):
        domain = [Process]
        range = [str]

    class process_conditions(DataProperty):  # Список параметров
        domain = [Process]
        range = [str]

    class process_materials(ObjectProperty):
        domain = [Process]
        range = [Material]

    class process_equipment(ObjectProperty):
        domain = [Process]
        range = [Equipment]

    class process_related_works(ObjectProperty):
        domain = [Process]
        range = [Publication | Experiment]

    # ==========================================
    # 9. СВОЙСТВА ДЛЯ КЛАССА PROPERTY
    # ==========================================
    class property_name(DataProperty, FunctionalProperty):
        domain = [Property]
        range = [str]

    class property_conditions(DataProperty):  # Список параметров
        domain = [Property]
        range = [str]

    class property_materials(ObjectProperty):
        domain = [Property]
        range = [Material]

    class property_related_works(ObjectProperty):
        domain = [Property]
        range = [Publication | Experiment]

# --- ДЕМОНСТРАЦИЯ ЗАПОЛНЕНИЯ ДАННЫМИ ---
with onto:
    # Создаем страну и предприятие
    russia = Country("Russia")
    mining_plant = Facility("Nornickel_Plant", facility_name="Завод Норникель", facility_country=russia)

    # Создаем эксперта
    ivanov = Expert("Expert_Ivanov",
                    expert_name="Иванов И.И.",
                    expert_qualification="Доктор технических наук",
                    expert_country=russia,
                    expert_facility=mining_plant)

    # Создаем публикацию
    article = Publication("Article_001",
                          pub_title="Инновационные методы флотации сульфидных руд",
                          pub_date=datetime.date(2026, 3, 1),
                          pub_country="Россия",
                          pub_language="Русский",
                          pub_type="статья",            # Пройдет валидацию по OneOf
                          pub_access_type="открытый",     # Пройдет валидацию по OneOf
                          pub_reliability="высокая",     # Пройдет валидацию по OneOf
                          pub_full_text="Полный текст исследования...",
                          pub_facility=mining_plant)

    # Заполнение списочных (Data) и объектных (Object) свойств
    article.pub_conclusions.extend(["Метод повышает извлечение никеля на 2%", "Снижены затраты реагентов"])
    article.pub_additional_materials.extend(["graph1.png", "data_table.xlsx"])
    article.has_author.append(ivanov)

    # Связываем публикацию обратно с экспертом
    ivanov.expert_publications.append(article)

# --- СОХРАНЕНИЕ ОНТОЛОГИИ ---
# Сохраняем в формате RDF/XML (можно открыть в Protégé)
onto.save(file="mining_ontology.owl", format="rdfxml")
print("Онтология успешно создана и сохранена в файл 'mining_ontology.owl'")

"""
### Ключевые особенности этой реализации:
* **`FunctionalProperty`**: Использовано для свойств, у которых может быть строго одно значение (например, название, дата, одно конкретное предприятие). Если свойство должно хранить список элементов (как выводы или авторы), `FunctionalProperty` **не** используется.
* **Логическое ИЛИ (`|`)**: Для свойств вроде `has_author` (где range — это `Expert` или `Team`) и `pub_keywords` использовано объединение классов с помощью оператора `|`.
* **Перечисления `OneOf`**: Ограничивают ввод типов публикаций, доступа и достоверности только строго заданными текстовыми значениями. Попытка записать туда другую строку вызовет ошибку при проверке ризонером.

Если вам потребуется автоматически **связать инверсные свойства** (например, чтобы при добавлении публикации автору она автоматически появлялась в списке его трудов), сообщите мне — я покажу, как настроить `inverse_property`. По какому сценарию планируется наполнять эту онтологию данными?"""

import datetime
from owlready2 import *

onto = get_ontology("http://example.org")

with onto:
    # Базовые классы
    class Publication(Thing): pass
    class Expert(Thing): pass
    class Team(Thing): pass
    class Facility(Thing): pass

    # --- ОПРЕДЕЛЕНИЕ СВОЙСТВ ---

    # 1. Связь: Публикация <-> Автор (Эксперт или Команда)
    class has_author(ObjectProperty):
        domain = [Publication]
        range = [Expert | Team]

    class expert_publications(ObjectProperty):
        domain = [Expert]
        range = [Publication]
        # Указываем, что это свойство инверсно свойству has_author
        inverse_property = has_author

    class team_publications(ObjectProperty):
        domain = [Team]
        range = [Publication]
        # Указываем инверсию и для команд
        inverse_property = has_author


    # 2. Связь: Публикация <-> Предприятие
    class pub_facility(ObjectProperty, FunctionalProperty):
        domain = [Publication]
        range = [Facility]

    class facility_publications(ObjectProperty):
        domain = [Facility]
        range = [Publication]
        inverse_property = pub_facility


    # 3. Связь: Эксперт <-> Предприятие
    class expert_facility(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Facility]

    class facility_employees(ObjectProperty):
        domain = [Facility]
        range = [Expert]
        inverse_property = expert_facility


    # 4. Связь: Команда <-> Предприятие
    class team_facility(ObjectProperty, FunctionalProperty):
        domain = [Team]
        range = [Facility]

    class facility_teams(ObjectProperty):
        domain = [Facility]
        range = [Team]
        inverse_property = team_facility


# --- ДЕМОНСТРАЦИЯ АВТОМАТИЧЕСКОГО СВЯЗЫВАНИЯ ---
with onto:
    # Создаем объекты
    nornickel = Facility("Nornickel_Holding")
    petrov = Expert("Expert_Petrov")
    report = Publication("Technical_Report_2026")

    print("=== ДО СВЯЗЫВАНИЯ ===")
    print(f"Сотрудники завода: {nornickel.facility_employees}")
    print(f"Публикации Петрова: {petrov.expert_publications}")
    print(f"Публикации завода: {nornickel.facility_publications}\n")

    # Достаточно задать связь ТОЛЬКО С ОДНОЙ стороны:
    petrov.expert_facility = nornickel  # Устраиваем Петрова на завод
    report.has_author.append(petrov)    # Назначаем Петрова автором отчета
    report.pub_facility = nornickel     # Привязываем отчет к заводу

    print("=== ПОСЛЕ ОДНОСТОРОННЕГО ЗАПОЛНЕНИЯ ===")
    # Owlready2 автоматически заполнил обратные списки:
    print(f"Сотрудники завода (заполнилось само): {nornickel.facility_employees}")
    print(f"Публикации Петрова (заполнилось само): {petrov.expert_publications}")
    print(f"Публикации завода (заполнилось само): {nornickel.facility_publications}")

# Сохраняем результат
onto.save(file="mining_inverse.owl", format="rdfxml")

"""Что изменилось:Свойство inverse_property: Конфигурирует двустороннюю синхронизацию.Управление памятью: Если вы в коде удалите Петрова из авторов публикации (report.has_author.remove(petrov)), он автоматически исчезнет и из списка публикаций самого эксперта."""

from owlready2 import *

onto = get_ontology("http://example.org")

with onto:
    # Базовые классы
    class Experiment(Thing): pass
    class Process(Thing): pass
    class Property(Thing): pass

    # ==========================================
    # КЛАСС ДЛЯ СТРУКТУРИРОВАННЫХ ПАРАМЕТРОВ
    # ==========================================
    class Parameter(Thing):
        """Класс для хранения физических параметров и условий."""
        pass

    # Свойства данных для Параметра
    class param_name(DataProperty, FunctionalProperty):
        domain = [Parameter]
        range = [str]  # Например: "Температура", "Давление"

    class param_value(DataProperty, FunctionalProperty):
        domain = [Parameter]
        range = [float]  # Числовое значение (поддерживает и int, и float)

    class param_unit(DataProperty, FunctionalProperty):
        domain = [Parameter]
        range = [str]  # Например: "°C", "кПа", "МПа"

    # ==========================================
    # ОБНОВЛЕННЫЕ СВОЙСТВА ОБЪЕКТОВ ДЛЯ КЛАССОВ
    # ==========================================
    # Вместо DataProperty (списка строк) делаем ObjectProperty,
    # ведущее к нашему новому классу Parameter
    class has_condition(ObjectProperty):
        domain = [Experiment | Process | Property]
        range = [Parameter]


# ==========================================
# ДЕМОНСТРАЦИЯ: НАПОЛНЕНИЕ ДАННЫМИ
# ==========================================
with onto:
    # --- Эксперимент 1 (Высокотемпературный) ---
    exp1 = Experiment("Experiment_Flotation_HighTemp")

    t1 = Parameter("Temp_Param_1", param_name="Температура", param_value=250.0, param_unit="°C")
    p1 = Parameter("Press_Param_1", param_name="Давление", param_value=101.3, param_unit="кПа")

    exp1.has_condition.extend([t1, p1])

    # --- Эксперимент 2 (Низкотемпературный) ---
    exp2 = Experiment("Experiment_Flotation_LowTemp")

    t2 = Parameter("Temp_Param_2", param_name="Температура", param_value=25.0, param_unit="°C")

    exp2.has_condition.append(t2)

    # --- Технологический Процесс ---
    proc1 = Process("Smelting_Process")

    t3 = Parameter("Temp_Param_3", param_name="Температура", param_value=1350.0, param_unit="°C")

    proc1.has_condition.append(t3)


# ==========================================
# ФУНКЦИЯ ДЛЯ ФИЛЬТРАЦИИ ОБЪЕКТОВ
# ==========================================
def find_objects_by_condition(parameter_name, min_value=None, max_value=None, unit="°C"):
    """
    Ищет любые сущности (эксперименты, процессы и т.д.), у которых
    заданный параметр находится в указанном числовом диапазоне.
    """
    results = []

    # Проходим по всем сущностям онтологии, у которых есть свойство has_condition
    for obj in onto.individuals():
        if hasattr(obj, "has_condition"):
            for param in obj.has_condition:
                # Проверяем совпадение имени параметра и единицы измерения
                if param.param_name == parameter_name and param.param_unit == unit:

                    value = param.param_value
                    match = True

                    # Проверяем нижнюю границу (например, > 200)
                    if min_value is not None and value <= min_value:
                        match = False
                    # Проверяем верхнюю границу
                    if max_value is not None and value >= max_value:
                        match = False

                    if match:
                        results.append((obj, value))

    return results

# ==========================================
# ПРИМЕР ИСПОЛЬЗОВАНИЯ ФИЛЬТРА
# ==========================================
print("=== Фильтрация: Температура выше 200 °C ===")
filtered_data = find_objects_by_condition(parameter_name="Температура", min_value=200.0)

for obj, temp in filtered_data:
    # .name возвращает ID объекта, а .is_a[0].name — его класс (Experiment, Process и т.д.)
    print(f"Найдено: [{obj.is_a[0].name}] {obj.name} (Фактическая температура: {temp} °C)")

"""## итог"""

!pip install owlready2

import datetime
from owlready2 import *

# 1. Инициализация онтологии
onto = get_ontology("http://example.org")

with onto:
    # --- ВСПОМОГАТЕЛЬНЫЕ КЛАССЫ ---
    class Country(Thing): pass

    class Parameter(Thing):
        """Класс для структурированного хранения физ. параметров и условий."""
        pass

    # --- ОСНОВНЫЕ КЛАССЫ ОНТОЛОГИИ ---
    class Publication(Thing): pass
    class Expert(Thing): pass
    class Team(Thing): pass
    class Facility(Thing): pass
    class Experiment(Thing): pass
    class Material(Thing): pass
    class Equipment(Thing): pass
    class Process(Thing): pass
    class Property(Thing): pass

    # ==========================================
    # СВОЙСТВА ДЛЯ КЛАССА PARAMETER (ЧИСЛОВЫЕ УСЛОВИЯ)
    # ==========================================
    class param_name(DataProperty, FunctionalProperty):
        domain = [Parameter]
        range = [str]

    class param_value(DataProperty, FunctionalProperty):
        domain = [Parameter]
        range = [float]

    class param_unit(DataProperty, FunctionalProperty):
        domain = [Parameter]
        range = [str]

    # Свойство связи объектов с их условиями/параметрами
    class has_condition(ObjectProperty):
        domain = [Experiment | Process | Property | Equipment | Material]
        range = [Parameter]

    # ==========================================
    # 1. СВОЙСТВА ДЛЯ КЛАССА PUBLICATION
    # ==========================================
    class pub_title(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_date(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [datetime.date]

    class pub_country(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_language(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_type(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [OneOf(["статья", "обзор", "отчёт", "протокол", "патент", "справочник", "нормативный материал"])]

    class pub_access_type(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [OneOf(["открытый", "закрытый"])]

    class pub_reliability(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [OneOf(["высокая", "средняя", "низкая"])]

    class pub_conclusions(DataProperty):
        domain = [Publication]
        range = [str]

    class pub_full_text(DataProperty, FunctionalProperty):
        domain = [Publication]
        range = [str]

    class pub_additional_materials(DataProperty):
        domain = [Publication]
        range = [str]

    # --- ОБЪЕКТНЫЕ И ИНВЕРСНЫЕ СВОЙСТВА PUBLICATION ---
    class has_author(ObjectProperty):
        domain = [Publication]
        range = [Expert | Team]

    class pub_facility(ObjectProperty, FunctionalProperty):
        domain = [Publication]
        range = [Facility]

    class pub_keywords(ObjectProperty):
        domain = [Publication]
        range = [Material | Equipment | Experiment | Process | Property | Facility]

    # ==========================================
    # 2. СВОЙСТВА ДЛЯ КЛАССА EXPERT
    # ==========================================
    class expert_name(DataProperty, FunctionalProperty):
        domain = [Expert]
        range = [str]

    class expert_qualification(DataProperty, FunctionalProperty):
        domain = [Expert]
        range = [str]

    class expert_country(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Country]

    class expert_facility(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Facility]

    class expert_team(ObjectProperty, FunctionalProperty):
        domain = [Expert]
        range = [Team]

    class expert_publications(ObjectProperty):
        domain = [Expert]
        range = [Publication]
        inverse_property = has_author  # ИНВЕРСИЯ К АВТОРУ

    # ==========================================
    # 3. СВОЙСТВА ДЛЯ КЛАССА TEAM
    # ==========================================
    class team_name(DataProperty, FunctionalProperty):
        domain = [Team]
        range = [str]

    class team_country(ObjectProperty, FunctionalProperty):
        domain = [Team]
        range = [Country]

    class team_facility(ObjectProperty, FunctionalProperty):
        domain = [Team]
        range = [Facility]

    class team_members(ObjectProperty):
        domain = [Team]
        range = [Expert]
        inverse_property = expert_team  # ИНВЕРСИЯ К ЭКСПЕРТУ

    class team_publications(ObjectProperty):
        domain = [Team]
        range = [Publication]
        inverse_property = has_author  # ИНВЕРСИЯ К АВТОРУ

    # ==========================================
    # 4. СВОЙСТВА ДЛЯ КЛАССА FACILITY
    # ==========================================
    class facility_name(DataProperty, FunctionalProperty):
        domain = [Facility]
        range = [str]

    class facility_country(ObjectProperty, FunctionalProperty):
        domain = [Facility]
        range = [Country]

    class facility_teams(ObjectProperty):
        domain = [Facility]
        range = [Team]
        inverse_property = team_facility  # ИНВЕРСИЯ К КОМАНДЕ

    class facility_employees(ObjectProperty):
        domain = [Facility]
        range = [Expert]
        inverse_property = expert_facility  # ИНВЕРСИЯ К ЭКСПЕРТУ

    class facility_publications(ObjectProperty):
        domain = [Facility]
        range = [Publication]
        inverse_property = pub_facility  # ИНВЕРСИЯ К ПУБЛИКАЦИИ

    # ==========================================
    # 5. СВОЙСТВА ДЛЯ КЛАССА EXPERIMENT
    # ==========================================
    class experiment_name(DataProperty, FunctionalProperty):
        domain = [Experiment]
        range = [str]

    class experiment_data(DataProperty):
        domain = [Experiment]
        range = [str]

    class experiment_conclusions(DataProperty):
        domain = [Experiment]
        range = [str]

    class experiment_publications(ObjectProperty):
        domain = [Experiment]
        range = [Publication]

    class experiment_materials(ObjectProperty):
        domain = [Experiment]
        range = [Material]

    class experiment_processes(ObjectProperty):
        domain = [Experiment]
        range = [Process]

    class experiment_equipment(ObjectProperty):
        domain = [Experiment]
        range = [Equipment]

    # ==========================================
    # 6. СВОЙСТВА ДЛЯ КЛАССА MATERIAL
    # ==========================================
    class material_name(DataProperty, FunctionalProperty):
        domain = [Material]
        range = [str]

    class material_properties(ObjectProperty):
        domain = [Material]
        range = [Property]

    class material_related_works(ObjectProperty):
        domain = [Material]
        range = [Publication | Experiment]

    # ==========================================
    # 7. СВОЙСТВА ДЛЯ КЛАССА EQUIPMENT
    # ==========================================
    class equipment_name(DataProperty, FunctionalProperty):
        domain = [Equipment]
        range = [str]

    class equipment_properties(ObjectProperty):
        domain = [Equipment]
        range = [Property]

    class equipment_related_works(ObjectProperty):
        domain = [Equipment]
        range = [Publication | Experiment]

    # ==========================================
    # 8. СВОЙСТВА ДЛЯ КЛАССА PROCESS
    # ==========================================
    class process_name(DataProperty, FunctionalProperty):
        domain = [Process]
        range = [str]

    class process_description(DataProperty, FunctionalProperty):
        domain = [Process]
        range = [str]

    class process_inputs(ObjectProperty):
        domain = [Process]
        range = [Material]

    class process_outputs(ObjectProperty):
        domain = [Process]
        range = [Material]

    class process_equipment(ObjectProperty):
        domain = [Process]
        range = [Equipment]

    class process_related_works(ObjectProperty):
        domain = [Process]
        range = [Publication | Experiment]

    # ==========================================
    # 9. СВОЙСТВА ДЛЯ КЛАССА PROPERTY
    # ==========================================
    class property_name(DataProperty, FunctionalProperty):
        domain = [Property]
        range = [str]

    class property_materials(ObjectProperty):
        domain = [Property]
        range = [Material]

        inverse_property = material_properties  # ИНВЕРСИЯ К МАТЕРИАЛУ

    class property_related_works(ObjectProperty):
        domain = [Property]
        range = [Publication | Experiment]


# ==========================================
# ФУНКЦИЯ ФИЛЬТРАЦИИ ПО ЧИСЛОВЫМ УСЛОВИЯМ
# ==========================================
def find_by_numeric_condition(parameter_name, min_value=None, max_value=None, unit="°C"):
    """Ищет объекты, у которых физ. параметр находится в заданных границах."""
    results = []
    for obj in onto.individuals():
        if hasattr(obj, "has_condition"):
            for param in obj.has_condition:
                if param.param_name == parameter_name and param.param_unit == unit:
                    val = param.param_value
                    is_match = True
                    if min_value is not None and val <= min_value:
                        is_match = False
                    if max_value is not None and val >= max_value:
                        is_match = False
                    if is_match:
                        results.append((obj, val))
    return results

# ==========================================
# НАПОЛНЕНИЕ ТЕСТОВЫМИ ДАННЫМИ И ПРОВЕРКА
# ==========================================
with onto:
    # 1. Создаем инфраструктуру
    ru = Country("RU")
    factory = Facility("Nornickel_Kola", facility_name="Кольская ГМК", facility_country=ru)

    # 2. Создаем эксперта
    scientist = Expert("Dr_Smirnov", expert_name="Смирнов А.В.", expert_qualification="Главный технолог")

    # СВЯЗЫВАЕМ В ОДНУ СТОРОНУ: устраиваем Смирнова на завод
    scientist.expert_facility = factory

    # 3. Создаем высокотемпературный процесс плавки и условия к нему
    smelting = Process("Copper_Smelting_Process", process_name="Плавка медного концентрата")

    temp_condition = Parameter("High_Temp_1300", param_name="Температура", param_value=1300.0, param_unit="°C")
    smelting.has_condition.append(temp_condition)

    # 4. Создаем публикацию по этому процессу
    report = Publication("Tech_Report_04", pub_title="Отчет по плавке 2026", pub_type="отчёт")

    # СВЯЗЫВАЕМ В ОДНУ СТОРОНУ: привязываем отчет к заводу и автору
    report.pub_facility = factory
    report.has_author.append(scientist)


# ==========================================
# ТЕСТИРОВАНИЕ РЕЗУЛЬТАТОВ
# ==========================================
print("--- Проверка работы инверсных свойств ---")
# Проверяем, появились ли данные на заводе и у ученого автоматически
print(f"Сотрудники завода (заполнилось инверсией): {[e.expert_name for e in factory.facility_employees]}")
print(f"Публикации на заводе (заполнилось инверсией): {[p.pub_title for p in factory.facility_publications]}")
print(f"Публикации ученого (заполнилось инверсией): {[p.pub_title for p in scientist.expert_publications]}")

print("\n--- Проверка работы числовой фильтрации ---")
# Ищем процессы/эксперименты с температурой выше 1000 °C
high_temp_nodes = find_by_numeric_condition(parameter_name="Температура", min_value=1000.0)

for node, temperature in high_temp_nodes:
    # Исправлено: берем первый класс из списка .is_a
    class_name = node.is_a[0].name
    print(f"Найдено: [{class_name}] ID: '{node.name}', Название: '{node.process_name}' (Температура: {temperature} °C)")

# Сохраняем финальную сборку онтологии в файл
onto.save(file="mining_integrated.owl", format="rdfxml")

# ==========================================
# НАПОЛНЕНИЕ ТЕСТОВЫМИ ДАННЫМИ И ПРОВЕРКА
# ==========================================
with onto:
    # 1. Создаем инфраструктуру
    ru = Country("RU")
    factory = Facility("Nornickel_Kola", facility_name="Кольская ГМК", facility_country=ru)

    # 2. Создаем эксперта
    scientist = Expert("Dr_Smirnov", expert_name="Смирнов А.В.", expert_qualification="Главный технолог")

    # СВЯЗЫВАЕМ В ОДНУ СТОРОНУ: устраиваем Смирнова на завод
    scientist.expert_facility = factory

    # 3. Создаем высокотемпературный процесс плавки и условия к нему
    smelting = Process("Copper_Smelting_Process", process_name="Плавка медного концентрата")

    temp_condition_1 = Parameter("High_Temp_1300", param_name="Температура", param_value=1300.0, param_unit="°C")
    smelting.has_condition.append(temp_condition_1)

    # --- ДОБАВЛЯЕМ НОВЫЙ ЭКСПЕРИМЕНТ ---
    # Создаем объект эксперимента и задаем ему температуру выше 1000 °C
    lab_experiment = Experiment("Lab_Flotation_HighTemp", experiment_name="Лабораторное исследование обжига")

    temp_condition_2 = Parameter("High_Temp_1150", param_name="Температура", param_value=1150.0, param_unit="°C")
    lab_experiment.has_condition.append(temp_condition_2)

    # 4. Создаем публикацию по процессу плавки
    report = Publication("Tech_Report_04", pub_title="Отчет по плавке 2026", pub_type="отчёт")

    # СВЯЗЫВАЕМ В ОДНУ СТОРОНУ: привязываем отчет к заводу и автору
    report.pub_facility = factory
    report.has_author.append(scientist)


# ==========================================
# ТЕСТИРОВАНИЕ РЕЗУЛЬТАТОВ
# ==========================================
print("--- Проверка работы инверсных свойств ---")
# Проверяем, появились ли данные на заводе и у ученого автоматически
print(f"Сотрудники завода (заполнилось инверсией): {[e.expert_name for e in factory.facility_employees]}")
print(f"Публикации на заводе (заполнилось инверсией): {[p.pub_title for p in factory.facility_publications]}")
print(f"Публикации ученого (заполнилось инверсией): {[p.pub_title for p in scientist.expert_publications]}")

print("\n--- Проверка работы числовой фильтрации (Универсальный вывод) ---")
# Ищем любые сущности с температурой выше 1000 °C
high_temp_nodes = find_by_numeric_condition(parameter_name="Температура", min_value=1000.0)

for node, temperature in high_temp_nodes:
    # 1. Исправлено: берем первый класс из списка .is_a
    class_name = node.is_a[0].name

    # 2. Универсальное извлечение имени: проверяем process_name, затем experiment_name
    display_name = getattr(node, "process_name", None) or getattr(node, "experiment_name", "Без названия")

    print(f"Найдено: [{class_name}] ID: '{node.name}', Название: '{display_name}' (Температура: {temperature} °C)")

# Сохраняем финальную версию онтологии в файл
onto.save(file="mining_integrated.owl", format="rdfxml")

# ==========================================
# ИСПРАВЛЕННАЯ ФУНКЦИЯ ФИЛЬТРАЦИИ ПО ЧИСЛОВЫМ УСЛОВИЯМ
# ==========================================
def find_by_numeric_condition(parameter_name, min_value=None, max_value=None, unit="°C"):
    """Ищет УНИКАЛЬНЫЕ объекты, у которых физ. параметр находится в заданных границах."""
    results = []

    for obj in onto.individuals():
        if hasattr(obj, "has_condition"):
            for param in obj.has_condition:
                if param.param_name == parameter_name and param.param_unit == unit:
                    val = param.param_value
                    is_match = True

                    if min_value is not None and val <= min_value:
                        is_match = False
                    if max_value is not None and val >= max_value:
                        is_match = False

                    if is_match:
                        # Добавляем объект и значение, после чего прерываем внутренний цикл (break),
                        # чтобы не дублировать этот же объект, если у него есть другие подходящие параметры.
                        results.append((obj, val))
                        break

    return results


# ==========================================
# ТЕСТИРОВАНИЕ РЕЗУЛЬТАТОВ
# ==========================================
print("--- Проверка работы инверсных свойств ---")
print(f"Сотрудники завода: {[e.expert_name for e in factory.facility_employees]}")
print(f"Публикации на заводе: {[p.pub_title for p in factory.facility_publications]}")
print(f"Публикации ученого: {[p.pub_title for p in scientist.expert_publications]}")

print("\n--- Проверка работы числовой фильтрации (Универсальный и уникальный вывод) ---")
high_temp_nodes = find_by_numeric_condition(parameter_name="Температура", min_value=1000.0)

for node, temperature in high_temp_nodes:
    # ИСПРАВЛЕНО: добавлен индекс [0] для корректного получения имени класса
    class_name = node.is_a[0].name

    # Универсальное извлечение имени
    display_name = getattr(node, "process_name", None) or getattr(node, "experiment_name", "Без названия")

    print(f"Найдено: [{class_name}] ID: '{node.name}', Название: '{display_name}' (Температура: {temperature} °C)")

# Сохраняем финальную версию
onto.save(file="mining_integrated.owl", format="rdfxml")

# wikidata subdictionary

import json
import os
from collections import defaultdict
from tqdm import tqdm

FULL_CLASS_GRAPH_CACHE = "wikidata_full_class_graph.json"
WIKIDATA_JSONL = "/var/ccd/wikidata-ruen_t_filtered.jonsl"
OUTPUT_DICT = "metallurgy_dict.jsonl"


# === ШАГ 1: СБОР И СОХРАНЕНИЕ ПОЛНОЙ ИЕРАРХИИ КЛАССОВ ===
def build_and_cache_full_graph(jsonl_path, cache_path):
    # Граф: Родительский_Класс -> [Список его прямых подклассов]
    full_graph = defaultdict(list)
    print("Шаг 1: Чтение и построение ПОЛНОГО графа классов из дампа...")
    
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line in tqdm(f):
            if '"P279"' not in line: 
                continue
                
            entity = json.loads(line)
            entity_id = entity.get('id')
            claims = entity.get('claims', {})
            
            if 'P279' in claims:
                for parent_id in claims['P279']:
                    full_graph[parent_id].append(entity_id)
                    
    print(f"Полный граф построен. Уникальных родительских классов: {len(full_graph)}")
    print(f"Сохраняем полную иерархию в кэш: {cache_path}...")
    
    with open(cache_path, 'w', encoding='utf-8') as f:
        json.dump(full_graph, f, ensure_ascii=False)
        
    print("Полный граф успешно сохранен на диск.")
    return full_graph


# Проверяем наличие полной карты классов на диске
if os.path.exists(FULL_CLASS_GRAPH_CACHE):
    print(f" Найдена полная иерархия классов: {FULL_CLASS_GRAPH_CACHE}. Загружаем...")
    with open(FULL_CLASS_GRAPH_CACHE, 'r', encoding='utf-8') as f:
        # JSON превращает ключи в строки, defaultdict восстановим для удобства
        loaded_graph = json.load(f)
        class_graph = defaultdict(list, loaded_graph)
    print(f"Граф загружен. Всего родительских узлов: {len(class_graph)}")
else:
    # Строим и кэшируем полную карту, если её нет
    class_graph = build_and_cache_full_graph(WIKIDATA_JSONL, FULL_CLASS_GRAPH_CACHE)

'''
import json
import os
from collections import defaultdict

# --- НАСТРОЙКА ПУТЕЙ И ЦЕЛЕЙ ---
FULL_CLASS_GRAPH_CACHE = "wikidata_full_class_graph.json"
WIKIDATA_JSONL = "your_wikidata_dump.jsonl"
OUTPUT_DICT = "multilingual_industry_dict.jsonl"



# === ШАГ 1: ЗАГРУЗКА ИЛИ СБОР ПОЛНОЙ ИЕРАРХИИ КЛАССОВ ===
def build_and_cache_full_graph(jsonl_path, cache_path):
    full_graph = defaultdict(list)
    print("Шаг 1: Построение ПОЛНОГО графа классов из дампа...")
    
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line in f:
            if '"P279"' not in line: 
                continue
            entity = json.loads(line)
            entity_id = entity.get('id')
            claims = entity.get('claims', {})
            
            if 'P279' in claims:
                for parent_id in claims['P279']:
                    full_graph[parent_id].append(entity_id)
                    
    print(f"Полный граф построен. Всего родительских классов: {len(full_graph)}")
    print(f"Сохраняем полную иерархию в кэш: {cache_path}...")
    with open(cache_path, 'w', encoding='utf-8') as f:
        json.dump(full_graph, f, ensure_ascii=False)
    return full_graph


if os.path.exists(FULL_CLASS_GRAPH_CACHE):
    print(f" Найдена полная иерархия классов: {FULL_CLASS_GRAPH_CACHE}. Загружаем...")
    with open(FULL_CLASS_GRAPH_CACHE, 'r', encoding='utf-8') as f:
        class_graph = defaultdict(list, json.load(f))
else:
    class_graph = build_and_cache_full_graph(WIKIDATA_JSONL, FULL_CLASS_GRAPH_CACHE)

'''
# Обновленный список ваших целевых классов
TARGET_ROOTS = [
    'Q11344',     # chemical element
    'Q43460564',  # chemical entity
    'Q214609',    # material
    'Q10683158',  # substance
    'Q79529',     # chemical substance
    'Q10273457',  # equipment
    'Q1183543',   # appliance
    'Q500669',    # technical process
    'Q111752858', # physicochemical process
    'Q1293220',   # physical phenomenon
    'Q1799072',   # method
    'Q104637425', # material process
    'Q764285',    # chemical property
    'Q6256'       # country
]

# === ПРОМЕЖУТОЧНЫЙ ШАГ: ПОЛУЧЕНИЕ ПОДКЛАССОВ ===
def get_all_descendants(target_roots, subclass_graph):
    print(f"\nВычисляем подклассы для заданных {len(target_roots)} целей...")
    all_subclasses = set(target_roots)
    queue = list(target_roots)
    
    while queue:
        current = queue.pop(0)
        for child in subclass_graph.get(current, []):
            if child not in all_subclasses:
                all_subclasses.add(child)
                queue.append(child)
                
    print(f"Для ваших целей найдено {len(all_subclasses)} валидных подклассов.")
    return all_subclasses

valid_classes_set = get_all_descendants(TARGET_ROOTS, class_graph)


# === ШАГ 2: СБОР ИТОГОВОГО ДВУЯЗЫЧНОГО СЛОВАРЯ ===
def extract_dictionary(jsonl_path, valid_classes, output_path):
    print("\nШаг 2: Фильтрация дампа и сбор двуязычного словаря...")
    count = 0
    
    with open(jsonl_path, 'r', encoding='utf-8') as f_in, \
         open(output_path, 'w', encoding='utf-8') as f_out:
             
        for line in tqdm(f_in):
            if '"P31"' not in line:
                continue
                
            entity = json.loads(line)
            claims = entity.get('claims', {})
            p31_values = claims.get('P31', [])
            
            # Проверяем, относится ли сущность к выбранным веткам
            if any(parent in valid_classes for parent in p31_values):
                entity_id = entity.get('id')
                labels = entity.get('labels', {})
                
                # Извлекаем названия (Label) для RU и EN
                name_ru = labels.get('ru', {}).get('value', '')
                name_en = labels.get('en', {}).get('value', '')
                
                # Если у объекта вообще нет ни русского, ни английского имени — пропускаем
                if not name_ru and not name_en:
                    continue
                
                # Извлекаем синонимы (Aliases)
                aliases_data = entity.get('aliases', {})
                aliases_ru = [a['value'] for a in aliases_data.get('ru', [])]
                aliases_en = [a['value'] for a in aliases_data.get('en', [])]
                
                # Извлекаем описания (Descriptions)
                descriptions_data = entity.get('descriptions', {})
                desc_ru = descriptions_data.get('ru', {}).get('value', '')
                desc_en = descriptions_data.get('en', {}).get('value', '')
                
                # Формируем чистую структуру для словаря
                result_item = {
                    'id': entity_id,
                    'names': {
                        'ru': name_ru if name_ru else None,
                        'en': name_en if name_en else None
                    },
                    'aliases': {
                        'ru': aliases_ru,
                        'en': aliases_en
                    },
                    'descriptions': {
                        'ru': desc_ru if desc_ru else None,
                        'en': desc_en if desc_en else None
                    },
                    'matched_classes': [p for p in p31_values if p in valid_classes]
                }
                
                f_out.write(json.dumps(result_item, ensure_ascii=False) + '\n')
                count += 1
                
                if count % 100000 == 0:
                    print(f"Собрано объектов в словарь: {count}...")
                        
    print(f" Двуязычный словарь успешно сформирован! Всего объектов: {count}")

# Запуск сборщика словаря
extract_dictionary(WIKIDATA_JSONL, valid_classes_set, OUTPUT_DICT)
